"""Tests for SECQUOIA tracking format loaders.

CTC, Ultrack and btrack all end up in the same track dataframe. Each format
is given the same small lineage: track 1 over frames 0 to 2, dividing into
tracks 2 and 3 over frames 3 to 5. Since all three feed the same lineage
editing tools, the tests also check the three agree on the TrackNumber they
hand out.
"""

from __future__ import annotations

from types import SimpleNamespace

import numpy as np
import pandas as pd
import pytest
import tifffile

from SECQUOIA.core.tracking.track_data import (
    assign_track_numbers,
    collect_positions_to_track_df_parallel,
    ctc_to_long,
    load_ultrack_with_tracknumber,
    tracks_to_dataframe,
)

# Cell Tracking Challenge
BLOCKS = {
    # frame: {label: (row slice start, col slice start)}
    0: {1: (2, 2)},
    1: {1: (2, 2)},
    2: {1: (2, 2)},
    3: {2: (2, 2), 3: (6, 6)},
    4: {2: (2, 2), 3: (6, 6)},
    5: {2: (2, 2), 3: (6, 6)},
}


def write_ctc_folder(
    folder,
    res_track: str,
    blocks: dict[int, dict[int, tuple[int, int]]] = None,
) -> str:
    """Write a Cell-Tracking-Challenge style result folder and return its path."""
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "res_track.txt").write_text(res_track)

    blocks = BLOCKS if blocks is None else blocks
    for frame, labels in sorted(blocks.items()):
        mask = np.zeros((12, 12), dtype=np.uint16)
        for label, (row, col) in labels.items():
            mask[row : row + 3, col : col + 3] = label
        tifffile.imwrite(folder / f"mask{frame:03d}.tif", mask)
    return str(folder)


# "L B E P": label, first frame, last frame, parent label.
DIVIDING_RES_TRACK = "1 0 2 0\n2 3 5 1\n3 3 5 1\n"


@pytest.fixture
def ctc_folder(tmp_path) -> str:
    return write_ctc_folder(tmp_path / "ctc", DIVIDING_RES_TRACK)


def test_ctc_to_long_numbers_a_division_as_a_binary_tree(ctc_folder):
    df = ctc_to_long(ctc_folder)

    numbers = df.groupby("TrackNumber")["t"].agg(["min", "max"])
    assert numbers.loc[1].tolist() == [0, 2]  # parent
    assert numbers.loc[2].tolist() == [3, 5]  # first daughter
    assert numbers.loc[3].tolist() == [3, 5]  # second daughter


def test_ctc_to_long_reports_the_lineage_root_as_track_id(ctc_folder):
    df = ctc_to_long(ctc_folder)

    assert set(df["track_id"].unique()) == {1}


def test_ctc_to_long_returns_one_row_per_label_per_frame(ctc_folder):
    df = ctc_to_long(ctc_folder)

    assert len(df) == 9  # 3 parent frames + 3 frames x 2 daughters
    assert list(df.columns) == ["track_id", "t", "y", "x", "TrackNumber"]
    assert df["t"].tolist() == [0, 1, 2, 3, 3, 4, 4, 5, 5]


def test_ctc_to_long_reads_centroids_from_the_masks(ctc_folder):
    df = ctc_to_long(ctc_folder)

    parent = df[df["TrackNumber"] == 1]
    assert parent["y"].unique().tolist() == [3.0]
    assert parent["x"].unique().tolist() == [3.0]

    # The second daughter's block sits at rows/cols 6-8, centroid 7.
    second = df[df["TrackNumber"] == 3]
    assert second["y"].unique().tolist() == [7.0]


def test_ctc_to_long_accepts_a_header_row(tmp_path):
    """The loader sniffs for an alphabetic first line instead of assuming one."""
    with_header = "L B E P\n" + DIVIDING_RES_TRACK
    folder = write_ctc_folder(tmp_path / "hdr", with_header)

    assert ctc_to_long(folder).equals(
        ctc_to_long(write_ctc_folder(tmp_path / "nohdr", DIVIDING_RES_TRACK))
    )


def test_ctc_to_long_ignores_comment_lines(tmp_path):
    commented = "# generated by something\n" + DIVIDING_RES_TRACK
    folder = write_ctc_folder(tmp_path / "cmt", commented)

    assert len(ctc_to_long(folder)) == 9


def test_ctc_to_long_drops_frames_outside_a_label_lifespan(tmp_path):
    """A label present in a mask outside its B..E window is not a track row."""
    blocks = {frame: dict(labels) for frame, labels in BLOCKS.items()}
    blocks[0][3] = (6, 6)  # label 3 appears long before it is born at t=3
    folder = write_ctc_folder(tmp_path / "stray", DIVIDING_RES_TRACK, blocks)

    df = ctc_to_long(folder)

    assert df[(df["TrackNumber"] == 3) & (df["t"] == 0)].empty
    assert len(df) == 9


def test_ctc_to_long_requires_res_track(tmp_path):
    folder = tmp_path / "empty"
    folder.mkdir()
    with pytest.raises(FileNotFoundError, match="res_track.txt"):
        ctc_to_long(str(folder))


def test_ctc_to_long_requires_masks(tmp_path):
    folder = tmp_path / "nomasks"
    folder.mkdir()
    (folder / "res_track.txt").write_text(DIVIDING_RES_TRACK)
    with pytest.raises(FileNotFoundError, match="mask"):
        ctc_to_long(str(folder))


# Ultrack
def ultrack_frame(t_column: str = "t") -> pd.DataFrame:
    """The same dividing lineage in Ultrack's CSV layout."""
    rows = [
        (1, -1, 0),
        (1, -1, 1),
        (1, -1, 2),
        (2, 1, 3),
        (2, 1, 4),
        (2, 1, 5),
        (3, 1, 3),
        (3, 1, 4),
        (3, 1, 5),
    ]
    return pd.DataFrame(
        {
            "track_id": [r[0] for r in rows],
            "parent_track_id": [r[1] for r in rows],
            t_column: [r[2] for r in rows],
            "x": [3.0] * len(rows),
            "y": [3.0] * len(rows),
        }
    )


def write_ultrack_folder(folder, frame: pd.DataFrame) -> str:
    folder.mkdir(parents=True, exist_ok=True)
    frame.to_csv(folder / "tracks.csv", index=False)
    return str(folder)


def test_ultrack_numbers_a_division_as_a_binary_tree(tmp_path):
    folder = write_ultrack_folder(tmp_path / "ut", ultrack_frame())

    df = load_ultrack_with_tracknumber(folder)

    spans = df.groupby("TrackNumber")["t"].agg(["min", "max"])
    assert spans.loc[1].tolist() == [0, 2]
    assert spans.loc[2].tolist() == [3, 5]
    assert spans.loc[3].tolist() == [3, 5]


def test_ultrack_replaces_track_id_with_the_lineage_id(tmp_path):
    folder = write_ultrack_folder(tmp_path / "ut", ultrack_frame())

    df = load_ultrack_with_tracknumber(folder)

    assert set(df["track_id"].unique()) == {1}
    assert "parent_track_id" in df.columns  # source column is kept


@pytest.mark.parametrize("t_column", ["t", "frame", "time"])
def test_ultrack_accepts_any_of_the_known_time_columns(tmp_path, t_column):
    folder = write_ultrack_folder(tmp_path / t_column, ultrack_frame(t_column))

    df = load_ultrack_with_tracknumber(folder)

    assert len(df) == 9
    assert sorted(df["TrackNumber"].unique()) == [1, 2, 3]


def test_ultrack_concatenates_every_csv_in_the_folder(tmp_path):
    folder = tmp_path / "multi"
    folder.mkdir()
    frame = ultrack_frame()
    frame[frame["t"] < 3].to_csv(folder / "a.csv", index=False)
    frame[frame["t"] >= 3].to_csv(folder / "b.csv", index=False)

    df = load_ultrack_with_tracknumber(str(folder))

    assert len(df) == 9
    assert sorted(df["TrackNumber"].unique()) == [1, 2, 3]


def test_ultrack_treats_a_missing_parent_as_a_root(tmp_path):
    """A blank parent_track_id means "no parent", same as -1."""
    frame = ultrack_frame()
    frame.loc[frame["track_id"] == 1, "parent_track_id"] = np.nan
    folder = write_ultrack_folder(tmp_path / "nan", frame)

    df = load_ultrack_with_tracknumber(folder)

    assert set(df["track_id"].unique()) == {1}
    assert sorted(df["TrackNumber"].unique()) == [1, 2, 3]


def test_ultrack_returns_empty_for_a_folder_with_no_csvs(tmp_path):
    folder = tmp_path / "none"
    folder.mkdir()

    assert load_ultrack_with_tracknumber(str(folder)).empty


def test_ultrack_returns_empty_when_no_time_column_is_recognised(tmp_path):
    frame = ultrack_frame().rename(columns={"t": "timepoint"})
    folder = write_ultrack_folder(tmp_path / "notime", frame)

    assert load_ultrack_with_tracknumber(folder).empty


# btrack
def fake_track(
    track_id: int,
    frames: range,
    *,
    root: int | None = None,
    children: list[int] | None = None,
    is_root: bool = False,
):
    """A stand-in for a ``btrack`` Tracklet.

    The loader only ever reads these attributes, so duck typing keeps the
    tests free of HDF5 files and of btrack itself.
    """
    return SimpleNamespace(
        ID=track_id,
        root=root,
        children=children or [],
        is_root=is_root,
        start=min(frames),
        t=list(frames),
        x=[3.0] * len(frames),
        y=[4.0] * len(frames),
    )


@pytest.fixture
def btrack_lineage() -> list:
    """The same dividing lineage as a btrack track list."""
    return [
        fake_track(1, range(3), root=1, children=[2, 3], is_root=True),
        fake_track(2, range(3, 6), root=1),
        fake_track(3, range(3, 6), root=1),
    ]


def test_assign_track_numbers_numbers_a_division_as_a_binary_tree(
    btrack_lineage,
):
    assert assign_track_numbers(btrack_lineage) == {1: 1, 2: 2, 3: 3}


def test_assign_track_numbers_orders_daughters_by_birth_frame():
    """The daughter that appears first gets the even TrackNumber."""
    tracks = [
        fake_track(1, range(3), root=1, children=[9, 8], is_root=True),
        fake_track(8, range(5, 8), root=1),  # born later
        fake_track(9, range(3, 6), root=1),  # born earlier
    ]

    numbers = assign_track_numbers(tracks)

    assert numbers[9] == 2
    assert numbers[8] == 3


def test_assign_track_numbers_handles_several_independent_lineages():
    tracks = [
        fake_track(1, range(3), root=1, children=[2, 3], is_root=True),
        fake_track(2, range(3, 6), root=1),
        fake_track(3, range(3, 6), root=1),
        fake_track(7, range(6), root=7, is_root=True),
    ]

    numbers = assign_track_numbers(tracks)

    assert numbers == {1: 1, 2: 2, 3: 3, 7: 1}


def test_assign_track_numbers_ignores_children_outside_the_track_list():
    """A dangling child id must not create a phantom TrackNumber."""
    tracks = [
        fake_track(1, range(3), root=1, children=[2, 404], is_root=True),
        fake_track(2, range(3, 6), root=1),
    ]

    numbers = assign_track_numbers(tracks)

    assert numbers == {1: 1, 2: 2}
    assert 404 not in numbers


def test_assign_track_numbers_treats_a_missing_root_as_its_own():
    solo = fake_track(5, range(4), root=None)

    assert assign_track_numbers([solo]) == {5: 1}


def test_tracks_to_dataframe_flattens_to_one_row_per_frame(btrack_lineage):
    df = tracks_to_dataframe(btrack_lineage)

    assert list(df.columns) == ["track_id", "t", "TrackNumber", "x", "y"]
    assert len(df) == 9
    assert set(df["track_id"].unique()) == {1}
    assert df["t"].tolist() == [0, 1, 2, 3, 3, 4, 4, 5, 5]
    assert df["x"].unique().tolist() == [3.0]
    assert df["y"].unique().tolist() == [4.0]


def test_tracks_to_dataframe_carries_the_binary_tracknumbers(btrack_lineage):
    df = tracks_to_dataframe(btrack_lineage)

    spans = df.groupby("TrackNumber")["t"].agg(["min", "max"])
    assert spans.loc[1].tolist() == [0, 2]
    assert spans.loc[2].tolist() == [3, 5]
    assert spans.loc[3].tolist() == [3, 5]


def test_tracks_to_dataframe_of_nothing_still_has_the_schema():
    df = tracks_to_dataframe([])

    assert df.empty
    assert list(df.columns) == ["track_id", "t", "TrackNumber", "x", "y"]


# All three loaders must agree
def test_every_loader_produces_the_same_lineage_numbering(
    tmp_path, ctc_folder, btrack_lineage
):
    """CTC, Ultrack and btrack must not disagree about TrackNumber.

    The lineage editing tools (division, split, fuse, undo) navigate the
    TrackNumber tree arithmetically, so a loader that numbered differently
    would silently corrupt edits made after that import.
    """
    ctc = ctc_to_long(ctc_folder)
    ultrack = load_ultrack_with_tracknumber(
        write_ultrack_folder(tmp_path / "cmp", ultrack_frame())
    )
    btrack_df = tracks_to_dataframe(btrack_lineage)

    def spans(df):
        grouped = df.groupby("TrackNumber")["t"].agg(["min", "max"])
        return {int(k): tuple(v) for k, v in grouped.iterrows()}

    assert spans(ctc) == spans(ultrack) == spans(btrack_df)
    assert spans(ctc) == {1: (0, 2), 2: (3, 5), 3: (3, 5)}


# Collecting several positions
def test_collect_positions_reads_every_position_folder(tmp_path):
    parent = tmp_path / "experiment"
    for position in (1, 2):
        write_ctc_folder(parent / f"exp_p{position}", DIVIDING_RES_TRACK)

    df = collect_positions_to_track_df_parallel(str(parent), "CTC", workers=2)

    assert sorted(df["Position"].unique()) == [1, 2]
    assert len(df) == 18


def test_collect_positions_tags_rows_with_the_folder_position_number(tmp_path):
    parent = tmp_path / "experiment"
    write_ctc_folder(parent / "exp_p7", DIVIDING_RES_TRACK)

    df = collect_positions_to_track_df_parallel(str(parent), "CTC")

    assert df["Position"].unique().tolist() == [7]


def test_collect_positions_skips_folders_without_a_position_suffix(tmp_path):
    parent = tmp_path / "experiment"
    write_ctc_folder(parent / "exp_p1", DIVIDING_RES_TRACK)
    (parent / "Analysis").mkdir()  # no _p<number> suffix

    df = collect_positions_to_track_df_parallel(str(parent), "CTC")

    assert df["Position"].unique().tolist() == [1]


def test_collect_positions_of_nothing_returns_an_empty_frame(tmp_path):
    parent = tmp_path / "empty"
    parent.mkdir()

    assert collect_positions_to_track_df_parallel(str(parent), "CTC").empty


def test_collect_positions_supports_the_ultrack_format(tmp_path):
    parent = tmp_path / "experiment"
    write_ultrack_folder(parent / "exp_p3", ultrack_frame())

    df = collect_positions_to_track_df_parallel(str(parent), "Ultrack")

    assert df["Position"].unique().tolist() == [3]
    assert sorted(df["TrackNumber"].unique()) == [1, 2, 3]
